#:schema node_modules/wrangler/config-schema.json
name = "podcastafterlistening"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

# Uncomment to enable KV-based ISR caching
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<your-kv-namespace-id>"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
